name: Check EDT EPSI

on:
  schedule:
    # S'exécute à 18:00 UTC du dimanche au jeudi
    - cron: '0 18 * * 0-4'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lancer le Bot
        env:
          EPSI_USER: ${{ secrets.EPSI_USER }}
          EPSI_PASS: ${{ secrets.EPSI_PASS }}
          DISCORD_URL: ${{ secrets.DISCORD_URL }}
          DISCORD_URL_GAUTHIER: ${{ secrets.DISCORD_URL_GAUTHIER }}
          STOAT_URL: ${{ secrets.STOAT_URL }}
        run: python main.py
